name: 'Bump Version'
description: 'Fetches latest version, bumps, and outputs it based on last merged PR branch name'
inputs:
  repository:
    description: "Repository name"
    required: true
  access_token:
    description: "GitHub Access Token"
    required: true
  initial_version:
    required: false
    default: "0.0.0"
outputs:
  new_version:
    description: "New generated version"
    value: ${{ steps.bump-version.outputs.version }}
runs:
  using: "composite"
  steps:
    - id: bump-version
      run: ./ci/actions/bump-version/script.sh "${{ inputs.repository }}" "${{ inputs.access_token }}" "${{ inputs.initial_version }}"
      shell: bash
