name: 'Bump Version'
description: 'Fetches latest version, bumps, and outputs it based on last merged PR branch name'
inputs:
  repository:
    description: "Repository name"
    required: true
  access_token:
    description: "GitHub Access Token"
    required: true
  initial_version:
    required: false
    default: "0.0.0"
  tag_only:
    description: "Create only git tags without github releases"
    required: false
    default: false
outputs:
  new_version:
    description: "New generated version"
    value: ${{ steps.bump-version.outputs.version }}
runs:
  using: "composite"
  steps:
    - id: bump-version
      run: >
        INPUT_REPOSITORY="${{ inputs.repository }}"
        INPUT_ACCESS_TOKEN="${{ inputs.access_token }}"
        INPUT_INITIAL_VERSION="${{ inputs.initial_version }}"
        INPUT_TAG_ONLY="${{ inputs.tag_only }}"
        ./actions/bump-version/script.sh
      shell: bash
